### ISSUE TITLE
Chrome 115 issues?

### ISSUE THREAD

**Issue by tmm1** [SamuelScheit/puppeteer-stream#129] opened 2023-08-09 19:51 UTC
Is this working with latest chrome 115?

I heard some people saying only 114 works

I wonder if the udp deprecated apis got removed?

**Comment by SamuelScheit** [comment] 2023-08-26 12:40
duplicate of #100

**Closed by SamuelScheit** 2023-08-26 12:40 UTC

**Comment by tmm1** [comment] 2023-08-26 13:10
Chrome 116 is working again. Not sure what was going on but it was probably unrelated.
