### ISSUE TITLE
stream.pipe(file),  file content is empty??why?

### ISSUE THREAD

**Issue by ksharp1982** [SamuelScheit/puppeteer-stream#54] opened 2022-06-23 07:08 UTC
hello , i use the puppeteer-stream,  save the stream to file ,but the webm file  is empty !! Mac system,,thank you

**Comment by JijaProGamer** [comment] 2022-06-30 13:27
Can you show us the code you used?

**Comment by LameFront** [comment] 2023-01-13 10:32
I got the same problem. Usually, when the service starts for the first time, everything works fine, but if, after stopping, start the second time, the stream remains empty.  All in **Headless** mode

```javascript
page
    .setViewport({ width: 1920, height: 1080 })
    .then(() => page.goto(url, { waitUntil: "domcontentloaded" }))
    .then(() =>
      getStream(page, {
        audio: true,
        video: true,
        videoConstraints: {
          mandatory: {
            minWidth: 1920,
            minHeight: 1080,
            maxWidth: 1920,
            maxHeight: 1080,
          },
        },
      })
    )
    .then((stream) => {
      rooms[callId] = { stream };
      stream.pipe(file);
    })
```

**Comment by SamuelScheit** [comment] 2023-03-06 01:20
duplicate of #90

**Closed by SamuelScheit** 2023-03-06 01:20 UTC
