### ISSUE TITLE
videoConstraints Not works

### ISSUE THREAD

**Issue by Hotsixisbest** [SamuelScheit/puppeteer-stream#147] opened 2024-02-02 14:13 UTC
```js
const stream = await getStream(page, {
        video: true,
        audio: true,
        videoConstraints:{
            mandatory:{
                width: {
                    min:1920,
                    max:1920
                },
                height: {
                    min:1080,
                    max:1080
                }
            }
        },
        bitsPerSecond: 8000000
    });
```

But I always get 2160p video

**Comment by SamuelScheit** [comment] 2024-02-02 23:28
duplicate of #15

**Closed by SamuelScheit** 2024-02-02 23:28 UTC

**Comment by koka0630** [comment] 2024-03-05 15:16
@SamuelScheit 
hello, I'm facing this problem too.
I have seen [this comment](https://github.com/SamuelScheit/puppeteer-stream/issues/15#issuecomment-1023623740) and it does not appear to be resolved by this Pull Request #32 🤔 
Could you reopen this issue again?

here is my environment:
- OS: Linux(ubuntu)
- Browser: chromium
- puppeteer-stream: 3.0.5
- code:
```
  const stream = await getStream(page, {
    audio: true,
    video: true,
    audioBitsPerSecond: 44100,
    frameSize: 24,
    streamConfig: {
      immediateResume: false,
    },
    videoConstraints: {
      mandatory: {
        width: { exact: 800 },
        height: { exact: 600 },
      },
    },
  });
```
- result: frame size is equals to full screen size 1024x768

**Comment by koka0630** [comment] 2024-03-21 07:48
@SamuelScheit
could you check this issue? 🙏

**Comment by HoussemRabah** [comment] 2025-05-26 19:33
hello, I face the same issue can you re open it again please
os: WINDOWS 11
puppeteer-stream: 3.0.5
browser: chrome
